name: Deploy Django to EC2

on:
  push:
    branches:
      - main   # deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app || mkdir ~/app && cd ~/app
            git pull || git clone https://github.com/${{ github.repository }} .
            
            # Build Docker image
            docker build -t devops-demo:latest .

            # Stop old container (if running)
            docker stop devops-demo || true
            docker rm devops-demo || true

            # Run new container
            docker run -d -p 8000:8000 --name devops-demo devops-demo:latest
          EOF

